module.exports = tempData = [
  {
    title: "The Conjuring",
    year: 2013,
    director: "James Wan",
    duration: "1h 52min",
    genre: [],
    rate: 7.5,
    poster: "http://www.impawards.com/2013/posters/conjuring_ver2.jpg",
  },
  {
    title: "Fast and Furius X",
    year: 2023,
    director: "Louis Leterrier",
    duration: "2h 21min",
    genre: ["Action", "Adventure"],
    rate: 5.7,
    poster: "",
  },
  {
    title: "Inside Out",
    year: 2015,
    director: "Pete Docter",
    duration: "1h 34min",
    genre: ["Adventure"],
    rate: 8.1,
    poster: "",
  },
  {
    title: "The Joker",
    year: 2019,
    director: "Tod Phillips",
    duration: "2h 2min",
    genre: ["Adventure", "Comedy"],
    rate: 8.4,
    poster: "",
  },
  {
    title: "Shrek",
    year: 2001,
    director: "Andrew Adamson",
    duration: "1h 31min",
    genre: ["Comedy"],
    rate: 7.9,
    poster: "",
  },
  {
    title: "The Amazing Spider-Man",
    year: 2014,
    director: "Marc Webb",
    duration: "2h 22min",
    genre: ["Fantasy", "Sci-Fi"],
    rate: 6.6,
    poster: "",
  },
  {
    title: "Inception",
    year: 2010,
    director: "Christopher Nolan",
    duration: "2h 28min",
    genre: ["Action", "Adventure", "Sci-Fi"],
    rate: 8.8,
    poster: "",
  },
  {
    title: "The Dark Knight",
    year: 2008,
    director: "Christopher Nolan",
    duration: "2h 32min",
    genre: ["Action", "Crime", "Drama"],
    rate: 9.0,
    poster: "",
  },
  {
    title: "Pulp Fiction",
    year: 1994,
    director: "Quentin Tarantino",
    duration: "2h 34min",
    genre: ["Crime", "Drama"],
    rate: 8.9,
    poster: "",
  },
  {
    title: "Forrest Gump",
    year: 1994,
    director: "Robert Zemeckis",
    duration: "2h 22min",
    genre: ["Drama", "Romance"],
    rate: 8.8,
    poster: "",
  },
  {
    title: "The Shawshank Redemption",
    year: 1994,
    director: "Frank Darabont",
    duration: "2h 22min",
    genre: ["Drama"],
    rate: 9.3,
    poster: "",
  },
  {
    title: "Fight Club",
    year: 1999,
    director: "David Fincher",
    duration: "2h 19min",
    genre: ["Drama"],
    rate: 8.8,
    poster: "",
  },
  {
    title: "The Matrix",
    year: 1999,
    director: "Lana Wachowski, Lilly Wachowski",
    duration: "2h 16min",
    genre: ["Action", "Sci-Fi"],
    rate: 8.7,
    poster: "",
  },
  {
    title: "Interstellar",
    year: 2014,
    director: "Christopher Nolan",
    duration: "2h 49min",
    genre: ["Adventure", "Drama", "Sci-Fi"],
    rate: 8.6,
    poster: "",
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    director: "Peter Jackson",
    duration: "3h 21min",
    genre: ["Action", "Adventure", "Drama"],
    rate: 8.9,
    poster: "",
  },
  {
    title: "The Lord of the Rings: The Two Towers",
    year: 2002,
    director: "Peter Jackson",
    duration: "2h 59min",
    genre: ["Action", "Adventure", "Drama"],
    rate: 8.7,
    poster: "",
  },
  {
    title: "The Social Network",
    year: 2010,
    director: "David Fincher",
    duration: "2h",
    genre: ["Biography", "Drama"],
    rate: 7.7,
    poster: "",
  },
  {
    title: "Whiplash",
    year: 2014,
    director: "Damien Chazelle",
    duration: "1h 46min",
    genre: ["Drama", "Music"],
    rate: 8.5,
    poster: "",
  },
  {
    title: "Gladiator",
    year: 2000,
    director: "Ridley Scott",
    duration: "2h 35min",
    genre: ["Action", "Adventure", "Drama"],
    rate: 8.5,
    poster: "",
  },
  {
    title: "The Lion King",
    year: 1994,
    director: "Roger Allers, Rob Minkoff",
    duration: "1h 28min",
    genre: ["Animation", "Adventure", "Drama"],
    rate: 8.5,
    poster: "",
  },
];
